### NP Test

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('c:/3rd_project/data/images/movie/[메인장르_주요색상_임베딩] 영화포스터(2011.01-2023.07).xlsx', engine='openpyxl')
df

idx                                영화명         개봉일        등급       장르  \
0      4658                    잃어버린 마법의 섬 홋타라케  2011-01-02     전체관람가    애니메이션   
1      4660  극장판 메탈 베이블레이드 VS 태양 작열의 침략자 솔블레이즈  2011-01-05     전체관람가    애니메이션   
2      4661                             동자 대소동  2011-01-05     전체관람가   가족,코미디   
3      4662                             심장이 뛴다  2011-01-05  15세이상관람가      드라마   
4      4663                           내 친구의 소원  2011-01-06  15세이상관람가  코미디,드라마   
...     ...                                ...         ...       ...      ...   
7000  18416                              붉은 사막  2023-07-26  15세이상관람가      드라마   
7001  18417                              비닐하우스  2023-07-26  15세이상관람가       범죄   
7002  18418                              에고이스트  2023-07-26   청소년관람불가      드라마   
7003  18419         핑크퐁 시네마 콘서트3 : 진저브레드맨을 잡아라  2023-07-26     전체관람가    애니메이션   
7004  18420                             헌티드 맨션  2023-07-26  12세이상관람가   공포(호러)   

      대표국적                                                줄거리  \
0       일본  당신이 잃어버린 물건이 이 섬에 있어요!'고교생인 하루카(遙)는 어릴 때 돌아가신 ...   
1       일본  멸망한 아틀란티스를 부활시키고 지구를 구하려는 소년들이 악인들과 맞써 싸우는 모험과...   
2       한국  초등학교에서 말썽꾸러기인 동자와 친구들은 예절 교육을 받기 위해 예절 학교로 가게 ...   
3       한국  심장은 하나, 살려야 할 사람은 둘. 당신이라면 어떻게 하겠어?한 중년 여성이 뇌사...   
4       영국  나만 알고 있는 (내 친구의 소원)리버풀에 사는 단짝친구인 지기와 로비, 엄마와 단...   
...    ...                                                ...   
7000  이탈리아  고도성장시대의 살벌한 이탈리아의 공업도시에서 공장 기사인 남편 및 아들과 셋이 살아...   
7001    한국  비닐하우스에 살고 있는 ‘문정’은 아들과 함께 살 제대로 된 집을 구하기 위해 간병...   
7002    일본  14살에 어머니를 잃고 시골 마을에서 자신의 성 정체성을 숨기며 살던 '코스케.' ...   
7003    한국  “세상에서 가장 맛있는 아이스크림을 먹고 싶어!”아기상어가 원하는 최고의 아이스크림...   
7004    미국  디즈니 &amp; &lt;캐리비안의 해적&gt; 제작진의 오싹한 초대장! 뉴올리언스...   

                                                    이미지    메인장르  \
0     https://image.tmdb.org/t/p/original/5dwqy4Sawp...   애니메이션   
1     https://image.tmdb.org/t/p/original/laZBDBf0WO...   애니메이션   
2     https://image.tmdb.org/t/p/original/yURf9IfjoC...     코미디   
3     https://image.tmdb.org/t/p/original/eIjQUq8Tbr...     드라마   
4     https://image.tmdb.org/t/p/original/bAWWN79s1e...     코미디   
...                                                 ...     ...   
7000  https://image.tmdb.org/t/p/original/u9GdCKd4II...     드라마   
7001  https://image.tmdb.org/t/p/original/hVb49BvAYe...       -   
7002  https://image.tmdb.org/t/p/original/lXtlwEBcdO...     드라마   
7003  https://image.tmdb.org/t/p/original/9TfGkkcLpR...   애니메이션   
7004  https://image.tmdb.org/t/p/original/oYfssARSMG...  공포(호러)   

             color1         color2         color3 embedding1 embedding2  \
0     [255 255 255]  [  0 153 210]     [17 14 21]      애니메이션      애니메이션   
1        [25 21 20]  [251 251 251]  [135 134 129]      애니메이션      애니메이션   
2        [30 39 20]  [103  48  27]  [255 255 255]        드라마         액션   
3     [161 102  58]        [0 0 0]  [255 255 255]        드라마          -   
4     [255 255 255]     [37 27 18]  [238  43  49]          -        드라마   
...             ...            ...            ...        ...        ...   
7000     [11 13 12]  [243  52  24]  [170  35  32]     공포(호러)        드라마   
7001  [108 136 201]        [3 3 3]     [44 52 99]     공포(호러)        드라마   
7002     [ 9 52 87]     [21 21 13]  [226 199 188]        드라마        드라마   
7003  [144 230 255]  [240 148 199]  [246 231 210]      애니메이션      애니메이션   
7004        [0 0 2]     [13 16 59]  [ 52  61 154]          -         액션   

     embedding3  
0         애니메이션  
1         애니메이션  
2            액션  
3           드라마  
4        공포(호러)  
...         ...  
7000     공포(호러)  
7001        드라마  
7002        코미디  
7003      애니메이션  
7004         액션  

[7005 rows x 15 columns]

In [3]:
X = np.load('c:/3rd_project/data/images/movie/X_total_color.npy')
y = np.load('c:/3rd_project/data/images/movie/y_total_color.npy')

In [5]:
len(X)

7005

In [6]:
y

array(['애니메이션', '애니메이션', '코미디', ..., '드라마', '애니메이션', '공포(호러)'],
      dtype='<U6')

In [9]:
print(X[0])
print(y[0])

[[[245 255 255]
  [242 252 254]
  [246 255 255]
  ...
  [250 250 252]
  [254 255 255]
  [254 255 255]]

 [[194 217 231]
  [197 220 233]
  [194 216 229]
  ...
  [245 245 247]
  [240 241 243]
  [238 239 241]]

 [[193 217 227]
  [193 217 228]
  [194 216 227]
  ...
  [250 249 254]
  [249 250 252]
  [241 242 244]]

 ...

 [[241 242 244]
  [241 242 244]
  [241 242 244]
  ...
  [239 240 242]
  [240 240 242]
  [240 240 242]]

 [[241 242 244]
  [241 242 244]
  [241 242 244]
  ...
  [239 240 242]
  [240 240 242]
  [240 240 242]]

 [[241 242 244]
  [241 242 244]
  [241 242 244]
  ...
  [239 240 242]
  [240 240 242]
  [240 240 242]]]
애니메이션
