### 데이터 확인

In [1]:
import pandas as pd

df = pd.read_csv('c:/3rd_project/data/Train/movie_data_231010_total.csv')
df

idx                                영화명 embedding1 embedding2  \
0      4658                    잃어버린 마법의 섬 홋타라케      애니메이션      애니메이션   
1      4660  극장판 메탈 베이블레이드 VS 태양 작열의 침략자 솔블레이즈      애니메이션      애니메이션   
2      4661                             동자 대소동        드라마         액션   
3      4662                             심장이 뛴다        드라마          -   
4      4663                           내 친구의 소원          -        드라마   
...     ...                                ...        ...        ...   
7000  18416                              붉은 사막     공포(호러)        드라마   
7001  18417                              비닐하우스     공포(호러)        드라마   
7002  18418                              에고이스트        드라마        드라마   
7003  18419         핑크퐁 시네마 콘서트3 : 진저브레드맨을 잡아라      애니메이션      애니메이션   
7004  18420                             헌티드 맨션          -         액션   

     embedding3  vehicle  food  animal  bird  person  ...  color_5_r  \
0         애니메이션        0     0       0     0       1  ...     0.6157   
1         애니메이션        0     0       1     0       0  ...     0.6784   
2            액션        0     0       0     0       4  ...     0.7725   
3           드라마        0     0       0     0       0  ...     0.6471   
4        공포(호러)        0     0       0     0       3  ...     0.8863   
...         ...      ...   ...     ...   ...     ...  ...        ...   
7000     공포(호러)        0     0       0     0       1  ...     0.3804   
7001        드라마        0     0       0     0       1  ...     0.4392   
7002        코미디        0     0       0     0       2  ...     0.3843   
7003      애니메이션        0     1       1     0       0  ...     0.8549   
7004         액션        0     0       0     0       3  ...     0.3216   

      color_5_g  color_5_b  act_freq  ani_freq  com_freq  dra_freq  hor_freq  \
0        0.7529     0.8039         7         5         0         0         0   
1        0.2275     0.1725         0         4         0         0         0   
2        0.6627     0.5137        15         0        14         0         0   
3        0.4902     0.3373         1         0         0         1         0   
4        0.7333     0.6118         1         0         1         0         0   
...         ...        ...       ...       ...       ...       ...       ...   
7000     0.1529     0.1255         4         1         1         2         0   
7001     0.3412     0.4431         3         0         1         0         0   
7002     0.2941     0.2000         0         0         0         0         0   
7003     0.7176     0.2902        19        37         0         0         0   
7004     0.3137     0.5490         2         0         0         0         8   

      etc_freq   genre  
0            0   애니메이션  
1            0   애니메이션  
2            0     코미디  
3            0     드라마  
4            0     코미디  
...        ...     ...  
7000         0     드라마  
7001         3       -  
7002         0     드라마  
7003         0   애니메이션  
7004         0  공포(호러)  

[7005 rows x 41 columns]

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7005 entries, 0 to 7004
Data columns (total 41 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   idx                  7005 non-null   int64  
 1   영화명                  7005 non-null   object 
 2   embedding1           7005 non-null   object 
 3   embedding2           7005 non-null   object 
 4   embedding3           7005 non-null   object 
 5   vehicle              7005 non-null   int64  
 6   food                 7005 non-null   int64  
 7   animal               7005 non-null   int64  
 8   bird                 7005 non-null   int64  
 9   person               7005 non-null   int64  
 10  objects              7005 non-null   int64  
 11  electronic products  7005 non-null   int64  
 12  computer             7005 non-null   int64  
 13  sport                7005 non-null   int64  
 14  weapon               7005 non-null   int64  
 15  eating utensil       7005 non-null   i

In [3]:
df['genre'].value_counts()

genre
드라마       1925
-         1545
액션        1450
애니메이션      813
코미디        726
공포(호러)     546
Name: count, dtype: int64

In [4]:
# 장르 라벨링

from sklearn.preprocessing import LabelEncoder

# LabelEncoder 객체 생성
label_encoder = LabelEncoder()

print(df['genre'].unique())

# 'genre' 열을 라벨링하여 새로운 'label_genre' 열 생성
df['genre'] = label_encoder.fit_transform(df['genre'])
print(df['genre'].unique())

df

['애니메이션' '코미디' '드라마' '액션' '-' '공포(호러)']
[3 5 2 4 0 1]


idx                                영화명 embedding1 embedding2  \
0      4658                    잃어버린 마법의 섬 홋타라케      애니메이션      애니메이션   
1      4660  극장판 메탈 베이블레이드 VS 태양 작열의 침략자 솔블레이즈      애니메이션      애니메이션   
2      4661                             동자 대소동        드라마         액션   
3      4662                             심장이 뛴다        드라마          -   
4      4663                           내 친구의 소원          -        드라마   
...     ...                                ...        ...        ...   
7000  18416                              붉은 사막     공포(호러)        드라마   
7001  18417                              비닐하우스     공포(호러)        드라마   
7002  18418                              에고이스트        드라마        드라마   
7003  18419         핑크퐁 시네마 콘서트3 : 진저브레드맨을 잡아라      애니메이션      애니메이션   
7004  18420                             헌티드 맨션          -         액션   

     embedding3  vehicle  food  animal  bird  person  ...  color_5_r  \
0         애니메이션        0     0       0     0       1  ...     0.6157   
1         애니메이션        0     0       1     0       0  ...     0.6784   
2            액션        0     0       0     0       4  ...     0.7725   
3           드라마        0     0       0     0       0  ...     0.6471   
4        공포(호러)        0     0       0     0       3  ...     0.8863   
...         ...      ...   ...     ...   ...     ...  ...        ...   
7000     공포(호러)        0     0       0     0       1  ...     0.3804   
7001        드라마        0     0       0     0       1  ...     0.4392   
7002        코미디        0     0       0     0       2  ...     0.3843   
7003      애니메이션        0     1       1     0       0  ...     0.8549   
7004         액션        0     0       0     0       3  ...     0.3216   

      color_5_g  color_5_b  act_freq  ani_freq  com_freq  dra_freq  hor_freq  \
0        0.7529     0.8039         7         5         0         0         0   
1        0.2275     0.1725         0         4         0         0         0   
2        0.6627     0.5137        15         0        14         0         0   
3        0.4902     0.3373         1         0         0         1         0   
4        0.7333     0.6118         1         0         1         0         0   
...         ...        ...       ...       ...       ...       ...       ...   
7000     0.1529     0.1255         4         1         1         2         0   
7001     0.3412     0.4431         3         0         1         0         0   
7002     0.2941     0.2000         0         0         0         0         0   
7003     0.7176     0.2902        19        37         0         0         0   
7004     0.3137     0.5490         2         0         0         0         8   

      etc_freq  genre  
0            0      3  
1            0      3  
2            0      5  
3            0      2  
4            0      5  
...        ...    ...  
7000         0      2  
7001         3      0  
7002         0      2  
7003         0      3  
7004         0      1  

[7005 rows x 41 columns]

In [5]:
df['genre'].value_counts()

# 드라마    2
# -         0
# 액션      4
# 코미디    5
# 애니      3
# 공포      1

genre
2    1925
0    1545
4    1450
3     813
5     726
1     546
Name: count, dtype: int64

### 언더샘플링

In [6]:
RANDOM_STATE = 2023

In [7]:
df.columns[5:-1]

Index(['vehicle', 'food', 'animal', 'bird', 'person', 'objects',
       'electronic products', 'computer', 'sport', 'weapon', 'eating utensil',
       'bag', 'etc', 'brightness', 'color_1_r', 'color_1_g', 'color_1_b',
       'color_2_r', 'color_2_g', 'color_2_b', 'color_3_r', 'color_3_g',
       'color_3_b', 'color_4_r', 'color_4_g', 'color_4_b', 'color_5_r',
       'color_5_g', 'color_5_b', 'act_freq', 'ani_freq', 'com_freq',
       'dra_freq', 'hor_freq', 'etc_freq'],
      dtype='object')

In [8]:
train_cols = df.columns[5:-1]

X = df[train_cols]
y = df['genre']

from imblearn.under_sampling import RandomUnderSampler

X_sample, y_sample = RandomUnderSampler(random_state=RANDOM_STATE).fit_resample(X, y)
X_samp = pd.DataFrame(data=X_sample,columns=train_cols )
y_samp = pd.DataFrame(data=y_sample,columns=['genre'])

data_samp=pd.concat([X_samp,y_samp],axis=1)

data_samp["genre"].value_counts()

genre
0    546
1    546
2    546
3    546
4    546
5    546
Name: count, dtype: int64

In [9]:
data_samp

vehicle  food  animal  bird  person  objects  electronic products  \
2659        0     0       1     0       0        0                    0   
3888        0     0       0     0       1        1                    0   
2820        0     0       0     0       3        0                    0   
2768        0     0       1     0       0        0                    2   
3805        0     0       0     0       0        0                    0   
...       ...   ...     ...   ...     ...      ...                  ...   
2562        0     0       0     0       3        0                    0   
4044        0     0       0     0       0        0                    0   
4457        0     0       0     0       1        0                    0   
998         0     1       0     0       2        0                    0   
5562        0     0       1     0       0        0                    0   

      computer  sport  weapon  ...  color_5_r  color_5_g  color_5_b  act_freq  \
2659         0      0       0  ...     0.3373     0.3216     0.3216         4   
3888         0      0       0  ...     0.9412     0.1804     0.1255         6   
2820         0      0       0  ...     0.1373     0.1882     0.2745         1   
2768         0      0       0  ...     0.1373     0.6627     0.8431         9   
3805         0      0       0  ...     0.6157     0.5922     0.5765         0   
...        ...    ...     ...  ...        ...        ...        ...       ...   
2562         0      0       0  ...     0.3098     0.3647     0.4118        13   
4044         0      0       0  ...     0.9333     0.9098     0.8824        12   
4457         0      0       0  ...     0.8471     0.7882     0.7529         0   
998          0      0       0  ...     0.0588     0.0510     0.0863         8   
5562         0      0       0  ...     0.6549     0.3333     0.3412         3   

      ani_freq  com_freq  dra_freq  hor_freq  etc_freq  genre  
2659         0         0         0         0         2      0  
3888         0         1         0         0         4      0  
2820         0         0         0         0         0      0  
2768         0         0         3         0        15      0  
3805         1         0         0         0         0      0  
...        ...       ...       ...       ...       ...    ...  
2562         2        27         0         0         0      5  
4044         2        11         0         0         0      5  
4457         0         0         0         0         0      5  
998          0        18         0         0         0      5  
5562         1         2         0         0         0      5  

[3276 rows x 36 columns]

In [10]:
X = data_samp.iloc[:, :-1].values
y = data_samp.iloc[:, -1].values

In [11]:
X

array([[0., 0., 1., ..., 0., 0., 2.],
       [0., 0., 0., ..., 0., 0., 4.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [12]:
y

array([0, 0, 0, ..., 5, 5, 5])

In [13]:
data_samp

vehicle  food  animal  bird  person  objects  electronic products  \
2659        0     0       1     0       0        0                    0   
3888        0     0       0     0       1        1                    0   
2820        0     0       0     0       3        0                    0   
2768        0     0       1     0       0        0                    2   
3805        0     0       0     0       0        0                    0   
...       ...   ...     ...   ...     ...      ...                  ...   
2562        0     0       0     0       3        0                    0   
4044        0     0       0     0       0        0                    0   
4457        0     0       0     0       1        0                    0   
998         0     1       0     0       2        0                    0   
5562        0     0       1     0       0        0                    0   

      computer  sport  weapon  ...  color_5_r  color_5_g  color_5_b  act_freq  \
2659         0      0       0  ...     0.3373     0.3216     0.3216         4   
3888         0      0       0  ...     0.9412     0.1804     0.1255         6   
2820         0      0       0  ...     0.1373     0.1882     0.2745         1   
2768         0      0       0  ...     0.1373     0.6627     0.8431         9   
3805         0      0       0  ...     0.6157     0.5922     0.5765         0   
...        ...    ...     ...  ...        ...        ...        ...       ...   
2562         0      0       0  ...     0.3098     0.3647     0.4118        13   
4044         0      0       0  ...     0.9333     0.9098     0.8824        12   
4457         0      0       0  ...     0.8471     0.7882     0.7529         0   
998          0      0       0  ...     0.0588     0.0510     0.0863         8   
5562         0      0       0  ...     0.6549     0.3333     0.3412         3   

      ani_freq  com_freq  dra_freq  hor_freq  etc_freq  genre  
2659         0         0         0         0         2      0  
3888         0         1         0         0         4      0  
2820         0         0         0         0         0      0  
2768         0         0         3         0        15      0  
3805         1         0         0         0         0      0  
...        ...       ...       ...       ...       ...    ...  
2562         2        27         0         0         0      5  
4044         2        11         0         0         0      5  
4457         0         0         0         0         0      5  
998          0        18         0         0         0      5  
5562         1         2         0         0         0      5  

[3276 rows x 36 columns]

### 데이터 셋 나누기

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=RANDOM_STATE)

In [15]:
i = 153

real_genre = data_samp.iloc[i][-1]
new_data = data_samp.iloc[i][:-1].values  # Pandas Series를 NumPy 배열로 변환
new_data = new_data.reshape(1, -1)  # 2D 배열로 변환
new_data

array([[0.    , 0.    , 0.    , 0.    , 1.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.338 , 0.1922, 0.1961,
        0.3294, 0.5725, 0.4627, 0.6157, 0.0706, 0.0588, 0.0941, 0.4471,
        0.5373, 0.7804, 0.4392, 0.3412, 0.4431, 3.    , 0.    , 1.    ,
        0.    , 0.    , 3.    ]])

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# SVM 모델 생성
svm_classifier = SVC(kernel='linear', C=1.0)

# 모델 훈련
svm_classifier.fit(X_train, y_train)

SVC(kernel='linear')

In [17]:
import joblib

# SVM 모델을 저장
model_filename = "c:/3rd_project/model/svm_classifier.pkl"
joblib.dump(svm_classifier, model_filename)

['c:/3rd_project/model/svm_classifier.pkl']

In [18]:
# 모델 평가
y_pred = svm_classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {round(accuracy,4)}\n')

Accuracy: 0.8628



In [19]:
# 새로운 데이터에 대한 예측
labels = {0: 'etc',
          1: 'horror',
          2: 'drama',
          3: 'ani',
          4: 'action',
          5: 'comedy'
          }
num = [885, 3925, 1732, 409, 486, 551]

for i in num:
    real_genre = df.iloc[i][-1]
    new_data = df.iloc[i][5:-1].values  # Pandas Series를 NumPy 배열로 변환
    new_data = new_data.reshape(1, -1)  # 2D 배열로 변환

    KNN_predicted_genre = svm_classifier.predict(new_data)

    print(f'실제 장르: {labels[real_genre]}')
    print(f'KNN 모델-예측 장르: {labels[KNN_predicted_genre[0]]}\n')

실제 장르: comedy
KNN 모델-예측 장르: comedy

실제 장르: horror
KNN 모델-예측 장르: horror

실제 장르: comedy
KNN 모델-예측 장르: comedy

실제 장르: action
KNN 모델-예측 장르: action

실제 장르: action
KNN 모델-예측 장르: action

실제 장르: ani
KNN 모델-예측 장르: ani



In [ ]:
# 드라마    2       1905
# -         0       3662
# 액션      4       4849
# 코미디    5       5209
# 애니      3       5848
# 공포      1       274

In [ ]:
# 모델 불러오기
model_svm = joblib.load('c:/3rd_project/model/svm_classifier.pkl')